Update apiAutomation-0x00 file

diff --git a/Advanced_shell/apiAutomation-0x00 b/Advanced_shell/apiAutomation-0x00
--- a/Advanced_shell/apiAutomation-0x00
+++ b/Advanced_shell/apiAutomation-0x00
@@ -1,3 +1,11 @@
 #!/bin/bash
-API_URL="https://pokeapi.co/api/v2/pokemon/"
-curl -s "$API_URL" -o data.json 2> error.txt
+API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"
+OUTPUT="data.json"
+
+# Make the request
+curl -s "$API_URL" -o "$OUTPUT"
+
+# Check if the request was successful
+if [ $? -ne 0 ]; then
+	echo "Failed to fetch for pikachu" >> errors.txt
+fi
